# This is a basic workflow to help you get started with Actions

name: TestCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run the code on server
      run: |
        cd ~/da-mis/da-mis-install
        python3 run.py --stop
        echo Stopping containers
        docker image rm kobofe_enketo_express 
        echo Deleting enketo image
        sudo rm -rf ../kobo-docker/.vols/enketo_express/
        echo Reruning Server
        python3 run.py
        echo enketo redeployement completed on $(TZ=":Asia/Kolkata" date)
        
